include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.freezed.dart
    # Exclude export staging directories explicitly
    - flutter_source_export_staging_1759937367/**
    - flutter_source_export_staging_1759937375/**
    - flutter_source_export_staging_1759937379/**

linter:
  rules:
    # Add or override lint rules here if needed
